name: Deploy Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: s4_docker

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          echo "${{ secrets.SECRET_ENV_FILE }}" > .env.production
          set -o allexport
          source .env.production
          set +o allexport

      - name: Load oauth.json
        run: |
          echo "${{ secrets.SECRET_OAUTH_JSON }}" > oauth.json
          set -o allexport
          source oauth.json
          set +o allexport

      - name: Docker Compose Up
        run: |
          docker compose build bot
          docker compose pull
          docker compose up -d --build