name: Deploy Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: s3_docker

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          echo "${{ vars.ENV_FILE }}" > .env.production
          set -o allexport
          source .env.production
          set +o allexport

      - name: Docker Compose Up
        env:
          OAUTH_JSON: ${{ vars.OAUTH_JSON }}
        run: |
          docker compose down
          docker compose build bot
          docker compose up -d