name: Deploy Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: s4_docker

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          echo "${{ vars.ENV_FILE }}" > .env.production
          set -o allexport
          source .env.production
          set +o allexport

      - name: Load oauth.json
        run: |
          echo "${{ vars.OAUTH_JSON }}" > oauth.json

      - name: Docker Compose Up
        run: |
          docker compose down
          docker compose build bot
          docker compose up -d