"""edit Track.spotify_refreshed_at to spotify_refresh_at

Revision ID: 04289c560c5c
Revises: 45a6cad48d51
Create Date: 2025-04-04 15:52:24.278867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04289c560c5c'
down_revision: Union[str, None] = '45a6cad48d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_refresh_at', sa.Integer(), nullable=False))
    op.drop_column('users', 'spotify_refreshed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_refreshed_at', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'spotify_refresh_at')
    # ### end Alembic commands ###
