"""add md5 checksum

Revision ID: 45a6cad48d51
Revises: 6c98fbc4386e
Create Date: 2025-04-04 15:02:09.437623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a6cad48d51'
down_revision: Union[str, None] = '6c98fbc4386e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('telegram_md5_checksum', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'telegram_md5_checksum')
    # ### end Alembic commands ###
