"""change creds storage

Revision ID: 59bdc35f510c
Revises: fc8875e47bc0
Create Date: 2025-04-09 23:28:32.649596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59bdc35f510c"
down_revision: Union[str, None] = "fc8875e47bc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("spotify_auth", sa.JSON(), nullable=False))
    op.add_column("users", sa.Column("ymusic_auth", sa.JSON(), nullable=False))
    op.drop_column("users", "ymusic_token")
    op.drop_column("users", "spotify_refresh_token")
    op.drop_column("users", "spotify_refresh_at")
    op.drop_column("users", "spotify_access_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "spotify_access_token", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_refresh_at", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("ymusic_token", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "ymusic_auth")
    op.drop_column("users", "spotify_auth")
    # ### end Alembic commands ###
